set ls=2
set tabstop=4
set shiftwidth=4
set expandtab
set hlsearch
set autoindent
set incsearch
set ruler
set number
set paste
syntax on

call pathogen#infect()
filetype plugin indent on

set nocompatible
set laststatus=2 

let g:Powerline_symbols = 'fancy'
let g:Powerline_symbols = 'unicode'

set background=dark
colorscheme solarized
set t_Co=256
set foldmethod=syntax
