[[ -s "/Users/peterpanaguiton/.rvm/scripts/rvm" ]] && source "/Users/peterpanaguiton/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

##
# Your previous /Users/peterpanaguiton/.bash_profile file was backed up as /Users/peterpanaguiton/.bash_profile.macports-saved_2012-08-24_at_14:51:31
##

# MacPorts Installer addition on 2012-08-24_at_14:51:31: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

